name: AtumNametagEdit
main: com.nametagedit.plugin.AtumNametagEdit
version: 4.5.20
api-version: 1.13
authors: [sgtcaze, Cory, Lorenzo0111, Aurelien30000]
softdepend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]
load: POSTWORLD
commands:
  ne:
    description: AtumNametagEdit commands
    aliases: [nte, nametagedit, ante]
